### ISSUE TITLE
Can't replace @OA to @SWG to call snippets

### ISSUE THREAD

**Issue by PHPTCloud** [qvtec/swagger-php-annotation#1]
Initially in project using `@SWG` alias for Open Api, but in your extension i can't replace `@OA` to call snippets :(

**Comment by qvtec** [comment]
I added completions type config, and you can change settings.
but just only replace OA to SWG etc.
Have a try!
![image](https://user-images.githubusercontent.com/55846114/128550660-bddf8307-f542-4c54-a27a-a957597bed5f.png)
