### ISSUE TITLE
Extension cant be found in settings

### ISSUE THREAD

**Issue by PHPTCloud** [qvtec/swagger-php-annotation#2]
I have problem with configuration of your extension through vscode settings. Nowhere show extension in `settings > extensions`.
Its not big problem, because i can open extension settings through `F1` or `Ctrl + Shift + X`, but its not comfortable

**Comment by qvtec** [comment]
I fixed title `Swagger-PHP Annotation`, and you can find `settings > extensions`.
![image](https://user-images.githubusercontent.com/55846114/128548854-9aa9a76d-46dd-4ea2-b64c-b619c01fb664.png)
v1.1.0
